spring: 
  application: 
    name: ApiGateway
server: 
  port: 5555

zuul: 
  routes: 
    ribbon: 
      path: /ribbon/** 
      serviceId: ribbon-consumer    
    feign:
      path: /feign/**
      serviceId: feign-consumer

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka,http://localhost:1112/eureka